// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSQa_wVZZPleiU_JU6iSV5WZxKT-hiHmQ',
    appId: '1:1047158654382:web:5094fdec6cf9121067743f',
    messagingSenderId: '1047158654382',
    projectId: 'tft-community-p3-61ba8',
    authDomain: 'tft-community-p3-61ba8.firebaseapp.com',
    storageBucket: 'tft-community-p3-61ba8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANPHaJ1Q79hfeCA4xn4tOqGbGQa84-Djw',
    appId: '1:1047158654382:android:c8e284c421a29d7167743f',
    messagingSenderId: '1047158654382',
    projectId: 'tft-community-p3-61ba8',
    storageBucket: 'tft-community-p3-61ba8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOhrfcazuTsJsVrSOUW3_hXj4WR_u6YVo',
    appId: '1:1047158654382:ios:b3d1964bca4d8c8167743f',
    messagingSenderId: '1047158654382',
    projectId: 'tft-community-p3-61ba8',
    storageBucket: 'tft-community-p3-61ba8.firebasestorage.app',
    iosBundleId: 'com.example.apiTftTrab1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOhrfcazuTsJsVrSOUW3_hXj4WR_u6YVo',
    appId: '1:1047158654382:ios:b3d1964bca4d8c8167743f',
    messagingSenderId: '1047158654382',
    projectId: 'tft-community-p3-61ba8',
    storageBucket: 'tft-community-p3-61ba8.firebasestorage.app',
    iosBundleId: 'com.example.apiTftTrab1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSQa_wVZZPleiU_JU6iSV5WZxKT-hiHmQ',
    appId: '1:1047158654382:web:1c5b0377099b21e067743f',
    messagingSenderId: '1047158654382',
    projectId: 'tft-community-p3-61ba8',
    authDomain: 'tft-community-p3-61ba8.firebaseapp.com',
    storageBucket: 'tft-community-p3-61ba8.firebasestorage.app',
  );
}
